### PR TITLE
Project initialization

### LINKED ISSUE #1: Use artipie parent pom
Let's use [parent pom](https://github.com/artipie/ppom):
```xml
<parent>
  <groupId>com.artipie</groupId>
  <artifactId>ppom</artifactId>
  <version>0.2.1</version>
</parent>
```

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #1

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#2](https://github.com/artipie/files-adapter/issues/2) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1b980cff-fdc5-49fb-b5c3-4274056a1a93); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
Job was finished in 16 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/files-adapter/issues/2#issuecomment-584513898))

@g4s8 Job `gh:artipie/files-adapter#2` is not assigned, can't get performer

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
