### PR TITLE
Updated ppom and http

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated ppom and http and used permissions from http.

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks

**Comment by olegmoz** [comment]
@yegor256 could you please touch `.rultor`, so we can create new release?

**Comment by yegor256** [comment]
@olegmoz done in 262c6a2

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5.1`

**Pull request merged**
