### PR TITLE
Updated ppom, asto and http

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated ppom, asto and http

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@g4s8 please merge, I'll release new version and update it in artipie

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.6.2`

**Comment by 0crat** [comment]
Job `gh:artipie/files-adapter#42` is not assigned, can't get performer

**Pull request merged**
